export const actionStrings = {
  authLogin: "AUTH_LOGIN",
  authLogout: "AUTH_LOGOUT",
  authRegister: "AUTH_REGISTER",
  getProduct: "GET_PRODUCT",
  getDetail: "GET_DETAIL_PRODUCT",
  createProduct: "CREATE_PRODUCT",
  editProduct: "EDIT_PRODUCT",
  deleteProduct: "DELETE_PRODUCT",
  getProfile: "USER_GET_PROFILE",
  editProfile: "USER_EDIT_PROFILE",
  getAllUser: "GET_ALL_USER",
  banUser: "BAN_USER",
  addToFavorite: "ADD_TO_FAVORITE",
  deleteFromFavorite: "DELETE_FROM_FAVORITE",
  addToCart: "ADD_TO_CART",
  deleteFromCart: "DELETE_FROM_CART",
  getHistory: "GET_TRANSACTIONS_HISTORY",
};
