import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Homepage from "@/assets/image/homepage.jpg";
import { useDispatch } from "react-redux";
import productAction from "@/redux/actions/product";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(productAction.getProductThunk());
  }, [dispatch]);
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Header />
      <main className="">
        <section className="flex flex-row w-screen">
          <article className="flex flex-col w-1/2 font-RedHat p-10 gap-4">
            <div className="text-3xl font-extrabold">Blend Media</div>
            <div className="text-xl">
              Blend Media Kreasi is a full service digital marketing agency that
              aims to increase our clients brand value by utilizing a
              data-driven approach to optimize the use of digital marketing
              channels.
            </div>
          </article>
          <article className="w-1/2">
            <Image alt="Homepage" src={Homepage} />
          </article>
        </section>
      </main>
      <Footer />
    </>
  );
}
